## WARNING: This file is just an example. Please do not use this file to deploy
##          anything. If any line was uncommented, unit test will fail!

## Main workload definition.
## Valid values: deployment, statefulset, daemonset, or cronjob
# workload: deployment

## Pod replica count. Does not apply to cronjobs. Defaults to 1
## NOTE: setting hpa.enabled to true will override this setting
# replicas: 1

## Image configuration
# imageName: nginx
# imagePullPolicy: IfNotPresent

## Scaling configuration. Should only apply when workload is deployment. In most
## cases, a 'RollingUpdate' is recommended. However, in the case of stateful
## workloads on deployments (i.e.: deployment workload with mounted persistent
## volumes), 'Recreate' would be recommended.
## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
# scalingConfig:
#   maxSurge: 1
#   maxUnavailable: 0
#   type: RollingUpdate

## Horizontal pod autoscaling configuration. Should only apply when workload is
## either deployment or stateful set. Currently only supports scaling by CPU
## utilization.
## TODO: add custom metrics support and memory utilization scaling
# hpa:
#   enabled: true
#   min: 1
#   max: 4
#   targetCPU: 80

## Inject configuration files or environment variables into deployment via
## configuration mapping
# configurations:
#   files:
#     - config.conf
#   strings:
#     key1: value1
#     key2: value2

## Additional container configurations. Use this section if multiple containers
## are required to run in the same Kubernetes pod
# additionalContainers:
#   - name: secondary-container
#     imageName: nginx
#     imagePullPolicy: IfNotPresent
#     configurations:
#       files:
#         - config3.sh
#       strings:
#         key3: value3
#         key4: value4
