{{- $backend := false }}
{{- if .Values.backendConfig }}
{{- if .Values.backendConfig.enabled }}
{{- $backend = true }}
{{- end }}
{{- end }}
{{- $iapSecret := false }}
{{- if .Values.secrets }}
{{- if .Values.secrets.enabled }}
{{- if and ( has "CLIENT_ID" .Values.secrets.variableNames ) ( has "CLIENT_SECRET" .Values.secrets.variableNames ) }}
{{- $iapSecret = true }}
{{- end }}
{{- end }}
{{- end }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-bc
  namespace: {{ .Release.Namespace }}
spec:
  {{- if $backend }}
  {{- if .Values.backendConfig.backendTimeout }}
  timeoutSec: {{ .Values.backendConfig.backendTimeout }}
  {{- end }}
  {{- end }}
  {{- if $backend }}
  {{- if .Values.backendConfig.connectionDrain }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.backendConfig.connectionDrain }}
  {{- end }}
  {{- end }}
  {{- if $backend }}
  {{- if .Values.backendConfig.cloudArmor }}
  securityPolicy:
    name: {{ .Values.backendConfig.cloudArmor }}
  {{- end }}
  {{- end }}
  logging:
    {{- if $backend }}
    {{- if .Values.backendConfig.logSampleRate }}
    enable: true
    sampleRate: {{ .Values.backendConfig.logSampleRate }}
    {{- else }}
    enable: false
    {{- end }}
    {{- else }}
    enable: false
    {{- end }}
  iap:
    {{- if $backend }}
    {{- if .Values.backendConfig.iap }}
    enabled: true
    {{- if $iapSecret }}
    oauthclientCredentials:
      secretName: {{ template "fullname" . }}-secret
    {{- else }}
    {{- fail "\n\nError --> CLIENT_ID or CLIENT_SECRET not found. Did you set them properly?\n" }}
    {{- end }}
    {{- else }}
    enabled: false
    {{- end }}
    {{- else }}
    enabled: false
    {{- end }}
  {{- if $backend }}
  {{- if .Values.backendConfig.sessionAffinity }}
  sessionAffinity:
    {{- if eq .Values.backendConfig.sessionAffinity "CLIENT_IP" }}
    affinityType: {{ .Values.backendConfig.sessionAffinity }}
    {{- else if eq .Values.backendConfig.sessionAffinity "GENERATED_COOKIE" }}
    affinityType: GENERATED_COOKIE
    affinityCookieTtlSec: {{ .Values.backendConfig.cookieTTL | default 60 }}
    {{- end }}
  {{- end }}
  {{- end }}
