{{- if not .Values.networking }}
{{- fail "\n\nError --> networking is a required field for all helm deployments\n" }}
{{- end }}
{{- if not .Values.networking.config }}
{{- fail "\n\nError --> networking.config is a required field for all helm deployments\n" }}
{{- end }}
{{- range $index, $networkConfig := .Values.networking.config }}
{{- if or $networkConfig.sslPolicy $networkConfig.httpsRedirect }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  labels:
    app: {{ template "fullname" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
  name: {{ template "fullname" $ }}-{{ $index }}-frontendconfig
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $networkConfig.httpsRedirect }}
  redirectToHttps:
    enabled: true
    responseCodeName: {{ $networkConfig.httpsRedirect }}
  {{- end }}
  {{- if $networkConfig.sslPolicy }}
  sslPolicy: {{ $networkConfig.sslPolicy }}
  {{- end }}
---
{{- end }}
{{- end }}
