{{- if .Values.storage }}
{{- if .Values.storage.enabled }}
{{- range $key, $volume := .Values.storage }}
{{- if not ( eq $key "enabled" ) }}
{{- if $volume.mountExistingDiskName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ template "fullname" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    {{- if $.Values.labelOverride }}
{{ toYaml $.Values.labelOverride | indent 4 }}
    {{- end }}
  name: {{ template "fullname" $ }}-{{ $key | lower }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ required "\n\nError --> storage size required\n" $volume.size }}
  claimRef:
    name: {{ template "fullname" $ }}-{{ $key | lower }}-pvc
    namespace: {{ $.Release.Namespace }}
  gcePersistentDisk:
    fsType: ext4
    pdName: {{ $volume.mountExistingDiskName }}
  {{- if $.Values.affinity }}
  {{- if $.Values.affinity.enabled }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
                - asia-east1-c
  {{- end }}
  {{- end }}
  {{- if not $volume.persistent }}
  persistentVolumeReclaimPolicy: Delete
  {{- else }}
  persistentVolumeReclaimPolicy: {{ $volume.persistent | ternary "Retain" "Delete" }}
  {{- end }}
  storageClassName: ""
  volumeMode: Filesystem
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
