{{- if .Values.autoscaling }}
{{- if .Values.autoscaling.enabled }}
{{- $scheduledScaling := false }}
{{- range $values := .Values.autoscaling.scaleBy }}
{{- if eq $values.metric "time" }}
{{- $scheduledScaling = true }}
{{- end }}
{{- end }}
{{- if $scheduledScaling }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - autoscaling
    attributeRestrictions: null
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - patch
{{- end }}
{{- end }}
{{- end }}
