{{- if .Values.autoscaling }}
{{- if .Values.autoscaling.enabled }}
{{- $scheduledScaling := false }}
{{- range $values := .Values.autoscaling.scaleBy }}
{{- if eq $values.metric "time" }}
{{- $scheduledScaling = true }}
{{- end }}
{{- end }}
{{- if $scheduledScaling }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
