secretValues:
    thisIsASecretVariableName: thisIsASecretVariable
    secretA: glakdsjhg
    secretB: glakdsjhg
    secretC: glakdsjhg
    CLIENT_ID: aaa
    CLIENT_SECRET: aaa
secretFiles:
    exampleSecret.sh: '#!/bin/bash
        echo "thisIsASecretFileValue"'
    secondarySecret.json: '{aa:bb}'
