secretValues:
    thisIsASecretVariableName: thisIsASecretVariable
    CLIENT_ID: aaa
    CLIENT_SECRET: aaa
secretFiles:
    thisIsASecretFileName.log: '#!/bin/bash
        echo "thisIsASecretFileValue"'
